name: Kubernetes
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
baseurl: /
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      version: "v1.4"
      githubbranch: "v1.4.12"
      docsbranch: "release-1.4"
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty

gems:
  - jekyll-redirect-from

include: [_headers]
